### ISSUE TITLE
account activation

### ISSUE THREAD

**Issue by mfyang** [sunscrapers/djoser#12]
I think we have a typo here --- ActivationView is misplaced by PasswordResetConfirmView.

``url(r'^activate$', views.PasswordResetConfirmView.as_view(), name='activate'),``

https://github.com/sunscrapers/djoser/blob/master/djoser/urls.py#L13

Another question is that why we need to use POST method for activation? The activation link is sent via email, and user's click supposes to activate the related account. Such click would generate a GET request, I suppose.

**Comment by haxoza** [comment]
@mfyang thanks a lot for reporting! I've just fixed it.

The main reason why we use POST method for activation is that we think GET method in any API should **not** change models state in database.

The other reason is this is just a REST API and opening the URL pointing to `ActivationView` in the browser doesn't make sense, because it replies with JSON (or other format). Assuming that you work for example on Single Page App the recommended way to handle the activation process is to create a separate page where the app triggers POST request to your backend API.

That's why we stick to this approach. However we are open to suggestions.
