### ISSUE TITLE
DFR3 User Activation

### ISSUE THREAD

**Issue by parietal-io** [sunscrapers/djoser#14]
I get an unauthorized error when clicking the email activation link in the sent email.  Do you know if this should work out-of-the-box?

**Comment by haxoza** [comment]
I suppose you directly use an url to [activation view](https://github.com/sunscrapers/djoser/blob/master/djoser/views.py#L173) which [expects POST request](https://github.com/sunscrapers/djoser/blob/master/djoser/utils.py#L39). When you open a link to this view in browser it makes a GET request which is simply not working.

Our assumption is that GET requests should not change the state of application. That's why the activation view expects POST in order to affect user model. Moreover it's REST API so if you open one of the endpoints in your browser it displays JSON response which is not something for regular user.

If you're working on single page application you need to create a new screen with separate url that generates POST request to your REST API.

If you really want to have view that activates user on GET request then you need to implement your own view, but remember to provide reasonable html response.

**Comment by parietal-io** [comment]
Thanks, that makes total sense.  Awesome project!
