### ISSUE TITLE
Add endpoint for deleting a user's account

### ISSUE THREAD

**Issue by nicodv** [sunscrapers/djoser#140]
Like the title suggests, it would be nice to give users the ability to delete their accounts.

It could be done with minor changes to the UserView. Just replace `RetrieveUpdateAPIView` with `RetrieveUpdateDestroyAPIView`, I think.

**Comment by joaoponceleao** [comment]
An endpoint to disable a user's account (rather than deleting it) would be useful.
However, i'm concerned about how this would be implemented. Particularly, I would like some warnings/best-practices in the docs along with such an endpoint regarding issues such as: how to deal with user-owned assets, objects, etc...

**Comment by lwm** [comment]
>  it would be nice to give users the ability to delete their accounts.

I think this is beyond the scope of `djoser`. 

`djoser` is trying to provide a RESTish interface for authentication, not user management.

**Comment by nicodv** [comment]
> djoser is trying to provide a RESTish interface for authentication, not user management.

If `djoser` offers registration and activation, then it should offer deactivation, no?

**Comment by joaoponceleao** [comment]
Deactivation and account deletion will always be very specific to each project. Its not as simple as disabling or deleting a user. So I can understand that djoser would not offer it.
However, in the same way that djoser offers activation with optional email confirmation required, perhaps it could implement a deactivation endpoint and view with email confirmation required as well (I imagine this would be a standard requirement across all projects. Obviously, with a caveat in the docs that all actions on user-specific objects, etc, have to be handled on a custom basis by the developer.

I still doubt that this will be implemented, as it would have to be, by definition, an incomplete endpoint - with users asking for all sorts of functionality after this. And you can already get this basic functionality with djoser's existing password reset views.
There are more pressing issues at the moment. JWT / OAuth, etc...

As a side-note, the best thing about djoser, is the lack of dependencies. I would be very concerned that by implementing user management, it would turn into a dependency nightmare like the django-rest-auth / allauth combination.

**Comment by piotr-szpetkowski** [comment]
Since with 527fbdfa48a7e1bcb487e662df24fab7ce0cfe70 I've introduced basic user delete, which will be improved post 1.0 I'm going to mark this issue as resolved.

Behavior of the delete is extremely customizable through the serializer. The basic implementation requires user to provide password, but one can always write a custom serializer with some other behavior (e.g. answer security question) and the delete itself can be customized using the `User.delete` so basically, it's as generic as it comes.

There is always field for improvement so if you have an idea, please specify it in a new issue.
