### ISSUE TITLE
Possible to set email field to unique ?

### ISSUE THREAD

**Issue by briva** [sunscrapers/djoser#160]
Hi guys,

Possible to turn the email field unique ?

**Comment by haxoza** [comment]
Hi @briva! It depends on what you would like to achieve:

1. If you mean email field in [default django user model](https://github.com/django/django/blob/master/django/contrib/auth/models.py#L366) I would say that you need to prepare your own serializers in order to take care about email uniqueness.
2. If you mean email field in your own custom user model based on django `AbstractBaseUser` I would recommend to mark that field as unique in model definition (by setting `unique=True`). If you also set this field as `User.USERNAME_FIELD` or if you append it to `User.REQUIRED_FIELDS` then djoser thanks to latest Django Rest Framework versions will take care about proper validators automatically.
