### ISSUE TITLE
Add a CHANGELOG

### ISSUE THREAD

**Issue by lwm** [sunscrapers/djoser#164]
Is there one? Can someone add one?

I saw a new `0.5.1` release and couldn't find the changes easily.

**Comment by mmarksnippety** [comment]
Good point! We don't have it. I'll add changelog soon. 
In 0.5.1 we update test configuration to Django 1.10 and Django REST Framework 3.4.*

**Comment by lwm** [comment]
Thanks @mmarksnippety!

**Comment by joaoponceleao** [comment]
If you're using grunt or gulp, there are plugins that automatically generate/update a changelog based on git commits.

**Comment by lwm** [comment]
> If you're using grunt or gulp

Any python based solutions!?

**Comment by joaoponceleao** [comment]
I don't know of any, but a quick google search showed this on first spot. Maybe worth a look:
https://pypi.python.org/pypi/gitchangelog

**Comment by lwm** [comment]
bump bump bump bump bump bump

**Comment by hvdklauw** [comment]
Indeed, please add a changelog/release notes. And if you want to autogenerate them please be sure your commit messages are correct for the format so it actually tells me if things will break if I update.

**Comment by lwm** [comment]
http://keepachangelog.com/en/0.3.0/

**Comment by lwm** [comment]
bump bump bump bump bump bump

**Comment by piotr-szpetkowski** [comment]
Hello! Thank you for poking about the topic - we've wanted to do that for some time and the day to do that has finally come. I'm going to add release notes via djoser Github releases (available at https://github.com/sunscrapers/djoser/releases).

Please note that it's ongoing process and there is some manual work to do. Also - unfortunately, idea about extracting release notes from commit messages is not good enough, because some commits didn't precisely specify what they are about.

When I'm done with properly describing releases I'll aggregate these notes into CHANGELOG file as proposed in issue.
