### ISSUE TITLE
Overide ActivationView

### ISSUE THREAD

**Issue by monicaphalswal** [sunscrapers/djoser#170]
1. I tried overriding 'ActivationView' by defining it in my own views and then assigning the view to the /activate' url. But it isn't working. Could anyone please provide a code snippet for the same. 
2. Also I want to override the email templates for which I created a 'djoser' directory in my 'templates' folder and placed the overridden files there. But it didn't work.
   Please help.

**Comment by haxoza** [comment]
Hi @monicaphalswal! Thanks for trying djoser!

Re 1: could you share any code so that we can have a look what does not work?

Re 2: Try to move your new email templates to your main 'templates' directory.  As far as I can see [we didn't put those default email templates to 'djoser' sub-directory](https://github.com/sunscrapers/djoser/tree/master/djoser/templates) (which is a bug I think, so thanks to pointing that out!).

**Comment by piotr-szpetkowski** [comment]
Hello @monicaphalswal. This issue has been inactive for quite some time already, so I'm going to close it assuming that you either managed to figure out solution for your problem or that you have found some other way to fix it.

I'd also like to recommend to submit user space questions at Q&A websites like http://stackoverflow.com/ where it's likely that you will get answer for your question faster and it can also be more comprehensive. Reason is that Github issues are focused on development related area e.g. bugs or features discussion, while Q&A sites are built to quickly answer questions.
