### ISSUE TITLE
Activation email with JWT Token as the token_generator

### ISSUE THREAD

**Issue by n3rdftw** [sunscrapers/djoser#178]
When using JWT Tokens with djoser, I can use it to register and login as expected. However, when using activation emails, the token_generator is set to default_token_generator from django.contrib.auth.tokens. 

It seems that after getting an activation url, the Token and UID from there is only good enough to set the user to "is_active", but doesn't have enough information there to continue the login process and automatically log the user in.

Is that the case?

**Comment by mcgeeco** [comment]
Yes that is the case. It would be viewed as a slightly greater security risk to provide a valid login token in that way, I believe.

**Comment by haxoza** [comment]
Hi @n3rdftw!

As @mcgeeco said this is exactly the case. In activation link itself or even after following this link, there should be no valid login token because somebody could steal this link and gain access to the account without providing credentials.

However if you really need to have this option you can override `ActivationView` class to return login token in response once activation link is validated successfully.
