### ISSUE TITLE
Disable RootView

### ISSUE THREAD

**Issue by davidtgq** [sunscrapers/djoser#179]
I can't think of any usage for RootView on my website, so it can be removed, but I'd prefer not to repeat urls.py just for this. Is there a way to disable RootView?

**Comment by haxoza** [comment]
There is no such way. For now you would need to create custom urls and copy-paste there what you need.

If you have any idea how to optionally get rid of root view then pull request is welcomed!

**Comment by piotr-szpetkowski** [comment]
Hello! Sorry for late reply. As you have mentioned, if you do not want to use `RootView` you do not have to, and even though solution might bring a bit of extra work it's worth it in my opinion.

```
import djoser.views

urlpatterns = [
    url(r'^users/actions/sign-up/$', djoser.views.RegistrationView), name='sign-up'),
    # ...
]
```
There are few pros of such approach besides being able to disable `RootView`:

1. You enable what you actually need and want in your API.
2. You have control over your URL patterns instead of using predefined.

Including and maintaining additional flag for enabling / disabling `RootView` would be too much effort for such small gain and also if we would provide a flag for `RootView` why wouldn't we for other potentially optional views such as `UserView`?

Therefore I'm going to close this, however if you / someone finds clean solution for this problem feel free to submit as a PR and we will take it from there.

**Comment by Sinkler** [comment]
Simple way to disable `RootView`: create somewhere file with urls without `RootView`, for example `utils/auth_urls.py`:

```
from djoser.urls.base import urlpatterns as base_urlpatterns
from djoser.urls.jwt import urlpatterns as jwt_urlpatterns

base_urlpatterns.pop()
urlpatterns = base_urlpatterns + jwt_urlpatterns
```

And then include it in your patterns:

```
urlpatterns = [
    path('auth/', include('utils.auth_urls')),
    # ...
]
```
