### ISSUE TITLE
A djoser fork with Python 2.6 support?

### ISSUE THREAD

**Issue by stugots** [sunscrapers/djoser#18]
Do you know of any djoser forks with Python 2.6 support?

I tried searching in Github, and on the web, but came up empty.  If there aren't any, I may fork it to add 2.6 support.

Thanks!

**Comment by stugots** [comment]
P.s. I made a fork that supports Python 2.6 That sounds so profound -- I had to change only one statement! :-)

**Comment by haxoza** [comment]
Great! We didn't want to focus on Python 2.6 as we hope the whole world move forward to 3.x. However we support Django 1.5 and DRF 2.4 which support Python 2.6.5 or above. That's why supporting Python 2.6 could be quite reasonable until we drop support for Django 1.5.

If you create pull request with your change and updated [Travis config file](https://github.com/sunscrapers/djoser/blob/master/.travis.yml) we are happy to merge it.

For now I'm closing this issue.
