### ISSUE TITLE
User Registration 

### ISSUE THREAD

**Issue by decentali89** [sunscrapers/djoser#180]
Thanks for great app
I am facing one problem i want to redirect to login or show user token on successful registration, how can i do this

**Comment by haxoza** [comment]
Hi @decentali89! I'm not sure exactly what you need however I will try to help.

1. Re redirect: you need to handle it on your own in your app (web app or mobile app, whatever) because djoser provides only REST API. Your frontend app should manage user flow accross the app.

2. Re show user token on successful registration: you would need to override `RegistrationView` class to return token in response on successful registration (when `RegistrationSerializer` is valid).

**Comment by decentali89** [comment]
Thanks alot

**Comment by Chuck-Aguilar** [comment]
@haxoza Hi.

I'm getting crazy with the "token Problem".  What should I do to override ```RegistrationView``` and ```RegistrationSerializer``` is on the djoser side. How can I know if it's valid? 

What I want to do is return a token and not the user. To do it, I would like to use this function 
`def create_token(user):
    jwt_payload_handler = api_settings.JWT_PAYLOAD_HANDLER
    jwt_encode_handler = api_settings.JWT_ENCODE_HANDLER

    payload = jwt_payload_handler(user)
    token = jwt_encode_handler(payload)

    return token`
But I don't know how to do it. 
Thanks!

**Comment by Chuck-Aguilar** [comment]
don't worry, I already found the answer :)

**Comment by Marpop** [comment]
@Chuck-Aguilar hey, can you provide the answer you have found?

**Comment by Marpop** [comment]
@Chuck-Aguilar hey, can you provide the answer you have found?
