### ISSUE TITLE
switching from session to basic authentication makes application vulnerable to csrf 

### ISSUE THREAD

**Issue by amineparis** [sunscrapers/djoser#185]
how to use csrf built-in protection after switching to basic since this feature is included in seesion authentication

**Comment by KaczuH** [comment]
Currently djoser supports only TokenAuthentication and it is possible to add JWT Authentication. See: [Djoser documentation](http://djoser.readthedocs.io/en/latest/authentication_backends.html)

Therefore your question is not quite valid in context of djoser usage.

Nevertheless we can discuss your problem:
    First of all:

1. Using of HTTP Basic Authentication is discouraged. See:

    -  [DRF documentation](http://www.django-rest-framework.org/api-guide/authentication/#basicauthentication)
    - [HTTP Basic Auth RFC](https://tools.ietf.org/html/rfc2617#section-3.1.1)
    - [OWASP](https://www.owasp.org/index.php/Basic_Authentication)

2. HTTP Basic authentication is not vulnerable to CSRF attack since it doesn't use cookies. You should use secure connection though. For further instructions see DRF and RFC documentation (Links above).


We hope that above information shed some light on your problem.

**Comment by piotr-szpetkowski** [comment]
We've removed basic auth from supported authentication backends, therefore I'm closing this issue.
