### ISSUE TITLE
Detect invalid reset token early, before asking the user to type new password

### ISSUE THREAD

**Issue by mnieber** [sunscrapers/djoser#186]
Trying to use a password reset token twice produces a 400 error. So far, so good.

However, I would like to detect this situation early, so I can prevent the situation where the user types their new password, only to find out that they need to request a new token (instead, I will tell them immediately).

Is that possible?

**Comment by piotr-szpetkowski** [comment]
Hello. To answer your question - yes it is entirely possible to do that, however it would most probably involve creating new API endpoint, which would test if given token is correct or to update existing endpoint.

The problem is that in case if your user have not yet used the token he will call the endpoint twice (or two endpoints) and while such a simple check should not bring overwhelming load onto your infrastructure it still seems suboptimal.

Other solution which is more of a workaround might be to store used tokens at front-end, but here also are some pitfalls - e.g. user can remove cached data, limited to single device...

**Comment by haxoza** [comment]
@piotr-szpetkowski In general I agree with your point of view. However with regards to:

> The problem is that in case if your user have not yet used the token he will call the endpoint twice (or two endpoints)

I think it is a matter of API client implementation. It can but it does not have to use this new additional endpoint.

**Comment by mnieber** [comment]
One possibility would be add an optional `dry-run` boolean argument that allows you to simulate the reset, without actually resetting the password

**Comment by piotr-szpetkowski** [comment]
Reference implementation provided with #204. Feature itself is not in scope of djoser core, however feel free to build an extension with what was provided in docs.

**Comment by mnieber** [comment]
Sorry for the late reply, it looks good!
