### ISSUE TITLE
possibility to changee email backend

### ISSUE THREAD

**Issue by faraggi** [sunscrapers/djoser#187]
Djoser settings should include an option to modify the email backend used for sending emails.
For the moment, it uses an in-house solution: `utils.UserEmailFactoryBase`
but the ideal situation would be to be able to override this.

**Comment by mcgeeco** [comment]
I'm open to correction, but as far as I'm aware that's not the email backend. It's just a factory for creating the actual emails themselves. They'll still be sent with whatever email backend you've specified in the Django settings.

**Comment by faraggi** [comment]
You're right, it is in fact, just a factory.
In that case, why ont just use the django default email templates?
I mean, django already has `activation`, `password_reset`, etc,  email templates.

Is this not possible?

**Comment by mcgeeco** [comment]
I haven't come across anything like this in the Django codebase but maybe you're right.

**Comment by faraggi** [comment]
I'm not sure I follow, is it not possible to use these? 

[https://github.com/django/django/tree/master/django/contrib/admin/templates/registration](https://github.com/django/django/tree/master/django/contrib/admin/templates/registration)

**Comment by mcgeeco** [comment]
Oh those are the templates, not the email objects. The factory just controls which templates to use and what variables to make available to them.

**Comment by piotr-szpetkowski** [comment]
Hello! Actually Djoser does not influence your chosen email backend. We're using a factory to simplify storing email templates in separate template files to improve code readability and to decouple the view layer from controller layer (as in MVC). Also it's totally fine to override the mentioned `utils.UserEmailFactoryBase` with e.g.:

```
class UserProfileEmailFactory(UserEmailFactoryBase):
    subject_template_name = 'user_profile_subject.txt'
    html_body_template_name = 'user_profile_body.txt'
```

Also if you'd like to actually change the email backend as in issue title you can for example use 
https://github.com/anymail/django-anymail to accomplish that.

I'm going to close the issue as the problem seems to be solved, however feel free to reply if you need to discuss this further.
