### ISSUE TITLE
Protocol is always http when the api is behind a SSL reverse proxy

### ISSUE THREAD

**Issue by rvignesh89** [sunscrapers/djoser#199]
Hi, I've just started to use your lib in my setup. It fits pretty well since I can customise the endpoints I want to use. However when it comes to generating the confirmation url on prod I'm afraid I'll always get a insecure url generated by djoser due the following check coupled with my setup.

```python
return cls(
            from_email=from_email,
            user=user or request.user,
            domain=django_settings.DJOSER.get('DOMAIN') or site.domain,
            site_name=django_settings.DJOSER.get('SITE_NAME') or site.name,
            protocol='https' if request.is_secure() else 'http',
            **context
        )
```

Since my API is behind a SSL reverse proxy the requests will not be secure. My current plan is to extend the View to pass in more context using which I can generate an expected url which will look something like this,

```python
class CustomPasswordResetView(PasswordResetView):
    """
    Override the Djoser view to provide an html template for password reset email.
    """

    def send_password_reset_email(self, user):
        email_factory = UserPasswordResetEmailFactory.from_request(self.request,
                                                                   user=user,
                                                                   real_protocol=settings.PROTOCOL)
        email_factory.html_body_template_name = 'password_reset_email_body.html'
        email = email_factory.create()
        email.send()
```

Do you think this is a good approach?

**Comment by piotr-szpetkowski** [comment]
That seems like a nice workaround and I'd probably do it in similar way, however there are few more ways to get out of this situation:

1. Initialize the factory on your own:
``` python
UserPasswordResetEmailFactory(from_email, user, protocol, ...)
```
It's not entirely great, because you have to do the job already done in `from_request`, and there you duplicate the codebase.

2. Override the factory class in your codebase.
``` python
class FooPasswordResetEmailFactory(UserPasswordResetEmailFactory):
    def __init__(self, from_email, user, protocol, domain, site_name, **context):
        self.protocol = 'https'
```
But hardcoding protocol is also not a great solution.

3. We might also allow to provide arbitrary protocol inside the `from_request` method by allowing optional `protocol` parameter. It wasn't necessary so far, but it seems like a nice thing to have. With that said - I'm able to push it to master any minute, if you need it, however you'd also have to install from git master, since it will take some time (weeks at least) until 0.7.0.

Please, let me know what turned out to be the best solution for your case.

**Comment by rvignesh89** [comment]
Thanks for the quick response! 

I'm going forward with your idea of overriding the factory class and reading the protocol from the settings. I think this approach works best because it feels more explicit where I override the protocol  created by djoser without adding too much code. Thanks for the suggestion 👍

**Comment by piotr-szpetkowski** [comment]
I've decided to go for it and to add `protocol` anyway as optional parameter to `from_request`, so cases like yours should be easier to handle and it actually makes sense to allow it (you might for example use/write a util inside your application layer to detect if your requests are passed through the SSL proxy). I'm going to leave this issue open for few more days in case of any questions or problems.

**Comment by haxoza** [comment]
Just for future reference: 1d68f61
