### ISSUE TITLE
[RFC] Rename the repository

### ISSUE THREAD

**Issue by piotr-szpetkowski** [sunscrapers/djoser#221]
Hi, in this kinda RFC issue I'd like to propose a respository name change. There are quite few reasons to do so:
1. People have a hard time searching and finding our project, because the name is kinda out of this world (https://en.wikipedia.org/wiki/Djoser)
2. The name is short, however it might not be the easiest one to remember.
3. SEO is almost non-existent and it would take a great effort to improve it.
4. For some time it was not being actively maintained and it might have brought a bad reputation. 

At the moment I do not have a proposition for a new name. First thing I'd like to do is to find out what everyone is thinking about the idea.

**Comment by pawelswiecki** [comment]
It's not necessary a bad idea (if github supports this kind of change, ofc). What are the names of Djoser's direct "competitors"?

**Comment by michalbon** [comment]
Yes, renaming seems reasonable for me.

**Comment by agagata** [comment]
I do not have a strong opinion on this.
You wrote a lot reasons why we should switch. What are the cons, then? Are there many blogposts/publications out there? If I remember correctly, djoser is mentioned somewhere in DRF docs.

**Comment by piotr-szpetkowski** [comment]
@pawelswiecki In my opinion our primary competitor is https://github.com/Tivix/django-rest-auth however its scope is a bit different.

@agagata The cons are as for example you have mentioned that the djoser have been included in some articles/documentation etc. over the net. Some of them can be updated, however it would take some time for people to catchup with the change. Also, some people might actually never get back to us and it is unfortunately something that we would have to live with.

**Comment by bartoszgrabski** [comment]
`django-drf-auth`

**Comment by KaczuH** [comment]
I'm not so sure that renaming will provide us with many gain.
Let's assume we have changed name of the project.
- we need to take care of proper and informative notes to community about that change
- some people will be confused
- will all links and references work?
- we start with basically new project (from perspective of community), mention on drf home page was huge boost for djoser, will it be doable again?

I prefer gaining users in organic way and not as disguise under another name.

**Comment by pawelswiecki** [comment]
Yes, the main downside is that some user will be stuck with the old version for ever. `pip install djoser --upgrade` will be useless, obviously.

**Comment by piotr-szpetkowski** [comment]
@KaczuH 
> we need to take care of proper and informative notes to community about that change

Yes, that's the hard part.

> some people will be confused

Obviously

> will all links and references work?

At the moment the plan is that we would rename the repository to something else and than fork it under **djoser** name and include a note about a project rename at the top of README and at the top of each docs page. We would also ask/PR DRF and django-packages maintainers to update name/URL in DRF docs. 

> we start with basically new project (from perspective of community), mention on drf home page was huge boost for djoser, will it be doable again?

With a new name by making the project actually visible in search engines and by stating our goal explicitly (and as we all know explicit is better) in long time period we should gain bigger community which would fuel faster development.

> I prefer gaining users in organic way and not as disguise under another name.

It's a difficult choice, however in my opinion it might actually be about survival or death.

**Comment by piotr-szpetkowski** [comment]
@sunscrapers/developers 

All name propositions aggregated in one post:
1. django-rest-framework-auth
2. drf-auth
3. django-drf-auth

Personally I like the first name, because it indicates that the project is directly based on DRF and it seems like a phrase people would actually lookup in search engines. What do you guys think?

**Comment by davidtgq** [comment]
How about `django-djoser`, as [recommended by the Django docs](https://docs.djangoproject.com/en/1.11/intro/reusable-apps/#packaging-your-app)? It would fix the issue of people not finding the name "djoser", it wouldn't waste the existing publicity/SEO, and it wouldn't confuse existing users as much.

For what it's worth: I wasn't aware of any bad reputation from inactive development, but even if so, I think we shouldn't try to hide or reset from that, only improve and be honest. `django-registration` had the same problem, they came back and people quickly understood to stop using `django-registration-redux`.

Also, with too many generic words like `rest-framework`, `auth`, `drf`, etc, I'd tend to forget the order of the words or which package is which since it resembles too closely the name of `django-rest-auth`.

**Comment by piotr-szpetkowski** [comment]
![django-rest-authentication](https://user-images.githubusercontent.com/18597734/29740124-8c69d31e-8a4f-11e7-997d-020dbe549cf5.png)

In my opinion, having a SEO-friendly name of the project would be a key to progress for such niche project. As you can see on the screenshot at the moment djoser is simply not findable via Google with a very simple and common phrase (despite the fact that most of our traffic comes from Google) . Therefore I find the name update essential for further growth.

`django-djoser` seems better than the `djoser` itself, however I think that we should go for something that's even better SEO-wise and maybe also easier to remember. Nevertheless I like the idea of waiting for #217

**Comment by davidtgq** [comment]
Ah I see, but I don't know if people actually search Google for a 3rd party package when they first look for a solution to authentication on DRF. Personally, I read the docs (first link in your screenshot) to see if there's a native solution inside django-rest-framework, then I saw the list of 3rd party packages at the bottom of that page, I compared all the packages and didn't like that most were too complicated/messy trying to do too many things. "Djoser" was unique and mostly intuitive compared to the other auth packages with generic and formal names, which is why I chose this. But ultimately, only the quality of the code matters to me, whatever the project name is :)

Also, in the meantime, I notice that the Github description is:

> REST implementation of Django authentication system.

I think it would be beneficial with a longer description, using keywords like "Login", "Registration", etc. The description on [DRF's website](http://www.django-rest-framework.org/api-guide/authentication/#djoser) is pretty good:

> Djoser library provides a set of views to handle basic actions such as registration, login, logout, password reset and account activation. The package works with a custom user model and it uses token based authentication. This is a ready to use REST implementation of Django authentication system.

Lastly, sorry if you already knew about this or have already implemented it, but maybe this is worth looking into: https://help.github.com/articles/search-engine-optimization-for-github-pages/

**Comment by piotr-szpetkowski** [comment]
After giving it a lot of thinking I've decided to abandon the idea of renaming the repository.

It might not be the easiest to remember or to relate it with authentication, but it's unique, it's short and it has some traffic. And it's awesome. I believe that I'd rather put more effort into proper descriptions, more documentation and other improvements than building the community from grounds up.

I've also thought a bit more on `django-djoser`, but it would suggest that djoser works with django itself, which is not true - it requires django-rest-framework to work and calling it `djangorestframework-djoser` in my opinion is not an option. So, while otherwise it might have been a nice idea it will not work in this case.
