### ISSUE TITLE
Inactive account and display message

### ISSUE THREAD

**Issue by sf27** [sunscrapers/djoser#232]
this line of code is never executed because the `authenticate` method always return None when the user is inactive https://github.com/sunscrapers/djoser/blob/master/djoser/serializers.py#L95

**Comment by piotr-szpetkowski** [comment]
Hi.
What you say is true, but only in case of Django >= 1.10:
> The new AllowAllUsersModelBackend and AllowAllUsersRemoteUserBackend ignore the value of User.is_active, while ModelBackend and RemoteUserBackend now reject inactive users.
https://docs.djangoproject.com/en/1.11/releases/1.10/#django-contrib-auth

We still support Django 1.8, so it is necessary to validate that user account is active.

Thank you for pointing it out, though, because it may not be obvious at first that it will need to be changed when 1.8 is dropped.

**Comment by sf27** [comment]
Yeah, it's true. Sure, no problem. I’m happy to help @piotr-szpetkowski 🙂

**Comment by piotr-szpetkowski** [comment]
A follow-up on this: DRF has dropped support for Django 1.8 and therefore we have done the same thing for 1.0.0. I've removed the obvious pieces, however I've postponed the full-cleanup to 1.1.0.
