### ISSUE TITLE
Enhance error message for not activated user

### ISSUE THREAD

**Issue by igsm** [sunscrapers/djoser#234]
Hi. Thanks for the djoser. I like it as it makes life easier unlike other packages.

There is one thing I have come across. I'd suggest to change a feedback message for a non-active user who tries to obtain jwt, because now it returns the following: 
```
{
    "non_field_errors": [
        "Unable to log in with provided credentials."
    ]
}
```
How can I detect if user tried wrong credentials or user has not just activated his account yet?

**Comment by piotr-szpetkowski** [comment]
Hello! Thank you for giving djoser a try.

Since Django 1.10 there are some changes relating to auth backends:
> The new AllowAllUsersModelBackend and AllowAllUsersRemoteUserBackend ignore the value of User.is_active, while ModelBackend and RemoteUserBackend now reject inactive users.
> https://docs.djangoproject.com/en/1.11/releases/1.10/#django-contrib-auth

So, in case of `django.contrib.auth.backends.ModelBackend` which is a default authentication backend your inactive user credentials are rejected during the `django.contrib.auth.authenticate` function call, and so that's why you have received such response. The best solution would probably be to simply change authentication backend to something more fitting - in your case it would probably be `django.contrib.auth.backends.AllowAllUsersModelBackend`.

If you believe that it's not a solution, please let me know.

**Comment by igsm** [comment]
Thank you for the answer. It can be a solution, although, I use 'account activation' logic via email and it remains to be important for me to recognise if user is inactive so that I can return an appropriate message. Also, one more question I have to address in that regards. How can I authenticate a user right after email confirmation, because no the response is 204 'Non Content'? Would I need to override activation view and serializer in order to return JWT (perhaps there is no great need for this, but in terms of user experience that makes it much smoother).

**Comment by haxoza** [comment]
Hi @igsm! Thanks for your feedback!

I understand that receiving a token just after activation (or just after registration in some cases) is very handy for ALI clients (frontend web apps or mobile apps). However there are two reasons we do not do that:

1) As you noticed we need to support a few API auth methods so it is very difficult do it in a very generic way. Especially there are DRF auth backends that are not based on any type of token, like basic auth or session. Also JWT differs from DRF `auth_token` method.

2) We believe that one endpoint should do one thing correctly and in a secure way. That's why we love to think about endpoints as they are orthogonal actions.

Now, knowing the above if you really need authenticating users in your flow after activation then we suggest to override `ActivationView` and generate JWT token to response on successful activation in a manual way.

@piotr-szpetkowski On the other hand I believe we can do the above customization easier in the future by utilizing custom serializers. `ActivationView` does not care about `self.serializer.data` but if it would care about that then the customization would be straightforward.

**Comment by igsm** [comment]
That's clear. Thanks for looking into my questions and providing answers.

**Comment by piotr-szpetkowski** [comment]
Awesome. The problem seems to be solved, so I'm going to close the issue.

In future we'll discuss the possibility of extending/overriding user activation with additional actions. Thanks for the help @haxoza.

**Comment by hammadzz** [comment]
Wait, so how can we send a more suitable error when a user has not activated their account yet? I see the challenge as usually a deleted user is just marked inactive. Has anyone implemented this? The original question was not answered.

**Comment by piotr-szpetkowski** [comment]
@hammadzz 
In Django >= 1.10 you will need to set a different auth backend (as I mentioned - most probably `django.contrib.auth.backends.AllowAllUsersModelBackend`) and https://github.com/sunscrapers/djoser/blob/master/djoser/serializers.py#L109 will catch it and return a 400 with a custom error, which can be customized via `'inactive_account'` error message.

**Comment by Kouff** [comment]
**app/serializers.py :**
```
from djoser.serializers import TokenCreateSerializer
from rest_framework.exceptions import ValidationError
from django.contrib.auth import authenticate

class CustomTokenCreateSerializer(TokenCreateSerializer):
    def validate(self, attrs):
        password = attrs.get("password")
        params = {settings.LOGIN_FIELD: attrs.get(settings.LOGIN_FIELD)}
        self.user = authenticate(**params, password=password)
        if not self.user:
            self.user = User.objects.filter(**params).first()
            if self.user and not self.user.check_password(password):
                self.fail("invalid_credentials")
        if self.user and not self.user.is_active:
            raise ValidationError("user is not active") # message that the user is not active
        elif self.user and self.user.is_active:
            return attrs
        self.fail("invalid_credentials")
```

**settings.py :**
```
DJOSER = {
    ... ,
    'SERIALIZERS': {
        ... ,
        'token_create': 'app.serializers.CustomTokenCreateSerializer', # path to serializer
    },
}
```

**Comment by 3skr0** [comment]
Why thumbs down ?

**Comment by 3skr0** [comment]
doesn't seems to work on my side
