### ISSUE TITLE
How to change localhost:8000 in password reset emails to front end URL?

### ISSUE THREAD

**Issue by Jamilammar** [sunscrapers/djoser#235]
I've spent all day on this and I just can't get it to work. I'm posting to /auth/password/reset/ and it sends the email just fine. Problem is I can't change the URL to the front end Domain or Site_Name.
Obviously, I need to change this to my frontend domain to set up the password reset. I've scoured the internet for 5 hours and still have nothing. 

I'm using:

DJOSER = {
    'DOMAIN': 'frontend.com',
    'SITE_NAME': 'Frontend',
    'PASSWORD_RESET_CONFIRM_URL': '#/password/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': '#/activate/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': True,
    'SERIALIZERS': {},
}

But it just seems to ignore DOMAIN and SITE_NAME no matter what I set it to. Thanks in advance

**Comment by piotr-szpetkowski** [comment]
Hi.
Inside docs you can find out that explicit email support is no longer part of djoser - http://djoser.readthedocs.io/en/latest/emails.html

`DOMAIN` and `SITE_NAME` settings have been moved to http://django-templated-mail.readthedocs.io/en/latest/settings.html

**Comment by Jamilammar** [comment]
Ah, ok. I guess if DOMAIN and SITE_NAME have nothing to do with Djoser, I'll follow your links. Thank you for the quick response.

**Comment by piotr-szpetkowski** [comment]
I think you have misunderstood what I tried to say.
Email support used to be directly built into the djoser package, but it wasn't a good design, because it wasn't part of this project's scope. Djoser's job ultimate goal is to provide a reference implementation of common REST endpoints relating to user authentication and that's the very reason why I've decided to delegate the task of email support to separate package, which is the [django-templated-mail](https://github.com/sunscrapers/django-templated-mail/) I've mentioned in my previous post.

Now, without email support in Djoser it didn't make sense to keep settings like `DOMAIN` or `SITE_NAME` in package settings, because the only place, where they have been used was code responsible for emails, so I've moved these settings to the [django-templated-mail](https://github.com/sunscrapers/django-templated-mail/) package.

So all you have to do is to define these settings in global scope instead of Djoser scope, e.g.:
```python
DOMAIN = 'frontend.com'
SITE_NAME = 'Frontend'

DJOSER = {
    'PASSWORD_RESET_CONFIRM_URL': '#/password/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': '#/activate/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': True,
}
```

Hopefully this clarifies the situation.

**Comment by Jamilammar** [comment]
Ahhh.. man, I definitely misunderstood. Stupid mistake on my part. I'm not very experienced with Python and Django. Once I put it outside of the DJOSER everything works fine.  Thanks again!

**Comment by piotr-szpetkowski** [comment]
Awesome! Glad I could help. In case of more problems don't hesitate to open new issues, it helps a lot.
