### ISSUE TITLE
UserAttributeSimilarityValidator does not work with djoser

### ISSUE THREAD

**Issue by jaap3** [sunscrapers/djoser#238]
When creating a new user (and possible when changing and/or resetting an existing user's password) the password validation is called in a way that's not compatible with Django's `UserAttributeSimilarityValidator`.

The `UserAttributeSimilarityValidator` is supposed to be called with the password *and* the user instance. Djoser only supplies the password, causing the `UserAttributeSimilarityValidator` to short circuit and return early (without a warning).

Since `UserAttributeSimilarityValidator` is in the default list of password validators in recent Django projects I would've expected it to work with Djoser as well.

**Comment by piotr-szpetkowski** [comment]
Hi @jaap3 
AFAIK `UserAttributeSimilarityValidator` is only useful if there is an authenticated user, which in case of user create or password reset is usually not true.

You are right though, that we're missing the support for such validators on `PasswordSerializer` and it will be fixed in 1.1 release.

**Comment by jaap3** [comment]
@piotr-szpetkowski I don't see why that particular validator would only be useful for logged in users? It works fine in all cases when using the normal django.contrib.auth forms as it only needs access to the user instance, which doesn't even have to be saved yet.

**Comment by piotr-szpetkowski** [comment]
Alright. I've finally had some time to take a proper look into the issue.
You were completely right and I guess that I've tried to resolve it quickly without putting enough effort to accurately analyze what this issue is truly about and I'm sorry about the misunderstanding.

I've pushed the d29566af17f9734f42a5a4c7f76473f118745116 which should resolve all the cases that were missing out. It would be awesome if you could verify that it solved the issue for you. I'm going to close the issue, but in case of any problems do not hesitate to open a new one / add a comment in here.
