### ISSUE TITLE
Changing Email Templates and Functionality

### ISSUE THREAD

**Issue by hammadzz** [sunscrapers/djoser#243]
I was unable to change the email templates for Activation, Confirmation, or PasswordReset email. I wanted to add more to the context like a url with a url scheme for an app (not just http:// or https://).

I created a pull request #242 but if there is another way to do this currently, it would be much appreciated. I prefer to stay on the release branch because #242 maybe rejected or take a while to be made into a release.

**Comment by piotr-szpetkowski** [comment]
Hi.
Fixed with c0402d45ab059b6734941a3edf7ca53584be5d67

Thank you for pointing out the issue and for your PR. I've decided to go slightly different way to keep it more consistent with existing flows. I'll also soon commit documentation for the new setting.
New version (i.e. 1.1) will be released about 8PM UTC+1.

**Comment by hammadzz** [comment]
Looks great to me

**Comment by hammadzz** [comment]
@piotr-szpetkowski I can add documentation pull request if that helps the release

**Comment by piotr-szpetkowski** [comment]
@hammadzz Docs are already here at http://djoser.readthedocs.io/en/latest/settings.html#email and I've just released 1.1.0. Please notify me if you experience any problems.
