### ISSUE TITLE
User is_active is always False when SEND_ACTIVATION_EMAIL is on

### ISSUE THREAD

**Issue by atkawa7** [sunscrapers/djoser#258]
User is_active is always False when SEND_ACTIVATION_EMAIL is on. The reason is these lines 
https://github.com/sunscrapers/djoser/blob/master/djoser/serializers.py#L159-L163. There is no way to turn it on since an inactive user always get permission denied
```python
 def validate(self, attrs):
        attrs = super(ActivationSerializer, self).validate(attrs)
        if not self.user.is_active:
            return attrs
        raise exceptions.PermissionDenied(self.error_messages['stale_token'])
```

**Comment by piotr-szpetkowski** [comment]
Hi @atkawa7 

Firstly - I apologize it took me so long to answer.

> There is no way to turn it on since an inactive user always get permission denied

Hmm, correct me if I'm wrong, however I believe it's the other way around. That is - if user is already active this piece of code will not run:

```python
if not self.user.is_active:
     return attrs
```

and it will cause the permission denied exception - hence 403 response, which makes sense, because we don't want to allow user to activate account if it is already active.

However if user hasn't activated account yet it will return `attrs` and proceed with the activation process. I believe this is desired behavior - what do you think?

**Comment by zefciu** [comment]
There is no input on this ticket for more than a year. I think there was some misunderstanding about the desired behavior. Closing.
