### ISSUE TITLE
Questions about /password/reset/confirm

### ISSUE THREAD

**Issue by stugots** [sunscrapers/djoser#26]
I've done some testing, and I'm puzzled about the /password/reset/confirm endpoint. I'm probably missing something obvious...

The password-reset email will contain a link of the form /password/reset/confirm/{id}/{token}. Your documentation says this is a POST endpoint. yet the browser will issue a GET when the user clicks on the link. How does this work?

The URLconf has the regex r'^password/reset/confirm$', yet the link will be /password/reset/confirm/{id}/{token} . The regex includes the EOL match, so I don't see how this can ever match the URL.

In the ActionViewMixin, it appears that request.DATA expects the uid and token to have been sent in via a query string. It also seems to expect the new_password to be present, otherwise self.get_serializer() returns False.  Is this correct?

**Comment by haxoza** [comment]
The main problem here is that the documentation is not clear enough.

Designing the API for djoser we made an important assumption that stands:  *GET method should __not__ change models state in database* (as mentioned [here](https://github.com/sunscrapers/djoser/issues/12#issuecomment-68706456) as well). 

This is the main reason we use POST methods in many endpoints like password reset, account activation link etc.

Regarding your issue first of all please notice that `PASSWORD_RESET_CONFIRM_URL` setting should be set on your own. It doesn't have any default value. In readme file there is only an example how it could look like.

Second thing is that opening the REST API endpoint in the browser doesn't make sense, because it replies with JSON (or other requested format). Assuming that you work on single page application the recommended way to handle password reset confirmation would be to create a separate page for that. `PASSWORD_RESET_CONFIRM_URL` setting should point to this page where posting the form by user should produce POST request to the API.

For now I'm closing this issue. I will create the separate issue to clarify those things in documentation.
