### ISSUE TITLE
Django 2.0 support

### ISSUE THREAD

**Issue by czert** [sunscrapers/djoser#260]
Hi,

django 2.0 is not listed among supported versions. Is this an omission, or is django 2.0 not compatible with djoser? If it's only an omission, the docs should be updated.

**Comment by piotr-szpetkowski** [comment]
Hi @czert .
Django 2.0 is supported, since we run unit tests against django master - I just didn't have time recently for maintenance tasks, because of djoser 2.0 development. In spare moment I'll create an **1.x** branch with few fixes, which have been requested in other issues, update travis versions matrix and update docs/readme to include django 2.0.

In other words - in case you run into any trouble running on django 2.0, please do report it via issues.

Let's keep this issue open until docs/travis are updated.

**Comment by czert** [comment]
Cool, thanks for the info.

**Comment by ttuygun** [comment]
@piotr-szpetkowski some problems with Django 2.x:
'UserCreateView' should either include a `queryset` attribute, or override the `get_queryset()` method.
most of the views affected

**Comment by axper** [comment]
@piotr-szpetkowski What about Django 2.1?

**Comment by dekoza** [comment]
@axper it works as well. As you can see in `tox.ini` - we run tests against Django 2.1 too.

**Comment by axper** [comment]
Can confirm, thanks for the awesome lib!
