### ISSUE TITLE
How not to show available endpoints?

### ISSUE THREAD

**Issue by igsm** [sunscrapers/djoser#267]
Hello. How can I not to show the list of available endpoints if someone accesses domain.com/auth/?
`urlpatterns = [
    (...),
    url(r'^auth/', include('djoser.urls')),
]`
In Django Rest for example, I can replace DefaultRouter with the SimpleRouter, eg.:
`router = SimpleRouter()`

but how to do it with Djoser?

**Comment by benjiboi214** [comment]
Djoser has explicit URL definitions, and doesn't use the router API from DRF.

Check in urls/base.py and you'll se that the base URL explicitly calls views.RootView.as_view()

`url(r'^$', views.RootView.as_view(), name='root'),`

All you should need to do is override that URL in your project to redirect to a 404. I did something similar because I didn't want users to be able to delete their accounts in my implementation.

in urls.py
`urlpatterns = [
    path('auth/users/delete/', user_delete_view)
]`

in views.py
`def user_delete_view(request):
    raise Http404()`

**Comment by zefciu** [comment]
Closing as the original question was answered.
