### ISSUE TITLE
OAuth2 POST: /o/{{ provider }}/

### ISSUE THREAD

**Issue by mark-slepkov** [sunscrapers/djoser#268]
Hey, guys. I'm gonna say you - I love your library. It includes almost all my auth willings. Thank you so much. 
But this is what I have found out:
Some auth providers (I tried facebook) require `redirect_uri`, but I met weird things using this endpoint.
`redirect_uri` does not came from config and does not takes from POST vars. It just equal url which I send request. In my case it equal `http://my-host.com/REST/auth/o/facebook` but facebook requires `http://my-host.com/auth/complete/facebook`. I propose add `redirect_uri` to POST parameters.

**Comment by zefciu** [comment]
Hmmm. I don't really understand your problem here. When you send a POST to the endpoint, there should be no more redirects. The social_core will just authenticate you and retrieve the data. If there is some problem with the process, you should file a ticket to https://github.com/python-social-auth/social-core rather than to djoser.

Feel free to reopen if there is something I don't understand.
