### ISSUE TITLE
Split user serializers

### ISSUE THREAD

**Issue by joshua-s** [sunscrapers/djoser#294]
In many applications, the response from `/users/<id>/` should contain a different set of fields than the response from `/users/me/`. This could be for privacy (not allowing other users access to confidential attributes on the user model) or simply because one requires a different set of information for the current user (e.g. settings).

It is possible to work around this issue with a custom viewset, but it does not work on legacy endpoints and adds unnecessary complexity to this common use case.

I propose that the serializer configuration for users be split into the following two settings:
- `user`
- `me`

**Comment by joshua-s** [comment]
I am willing to provide a PR if this feature is given a green light 🚦

**Comment by dekoza** [comment]
Please do. Just make sure this will be backward-compatible.

**Comment by joshua-s** [comment]
Sure thing!

**Comment by jaap3** [comment]
I just tried using this, but it didn't work for me... maybe this is because I have set up DRF using custom urlpatterns

I use `djoser.views.UserView` to emulate the `me` endpoint, this view always uses `request.user` as it's object, so I think it should use `settings.SERIALIZERS.current_user` as the `serializer_class` instead of `settings.SERIALIZERS.user`.

When I look at the urlpatterns shipped with djoser it looks like it also uses `djoser.views.UserView` for the `me` endpoint: https://github.com/sunscrapers/djoser/blob/127fe8d7c6187050ac76f2f8ded342641c9b0885/djoser/urls/base.py#L14

Am I missing something?
