### ISSUE TITLE
can update other user info with user token

### ISSUE THREAD

**Issue by ponyjack** [sunscrapers/djoser#303]
i get a token with "token/login"  user A
and then can update other user info with user A token
put users/2/ email=xxxx

**Comment by dekoza** [comment]
Does user A have admin rights?

**Comment by jpdlor** [comment]
Yes, bumped into this also. This seems a rather critical security breach for any project using stock routes and views.
Culprit is UserViewSet class used to handle any users/xx/ request. May be fixed by adding (either in base class or in a custom subclass) something like:
```
    def get_object(self):
        obj = super(CustomUserViewSet, self).get_object() # if subclass
        if self.action in ['retrieve', 'update'] and obj != self.request.user and not self.request.user.is_superuser:
            raise PermissionDenied
        return obj
```
(disclaimer: not thoroughly tested...)

**Comment by Alig1493** [comment]
I'd like to take up this issue.

**Comment by krnr** [comment]
bumped into this also. the reason is that `rest_framework.mixins.UpdateModelMixin` uses [`get_object()`](https://github.com/encode/django-rest-framework/blob/master/rest_framework/mixins.py#L67) method rather than Djoser-defined `get_instance()`.

    def get_instance(self):
        return self.request.user

I overrode this to set my own viewset with `get_object()` method, but yes - it's a serious security issue!
