### ISSUE TITLE
Bug when using custom serializers

### ISSUE THREAD

**Issue by matthiaswh** [sunscrapers/djoser#308]
Running Djoser 1.3.0 on Django 2.1.1

I can successfully create and use one custom serializer like so:

```
# users/serializers.py
class CustomUserCreateSerializer(UserCreateSerializer):
    class Meta:
        fields = tuple(User.REQUIRED_FIELDS) + (
            User.USERNAME_FIELD, User._meta.pk.name, 'password',
            'is_manager',
        )

# settings.py
DJOSER = {
    'SERIALIZERS': {
        'user_create': 'users.serializers.CustomUserCreateSerializer',
    },
}
```

But as soon as I create a second serializer I get an error:

```
# users/serializers.py
class CustomUserCreateSerializer(UserCreateSerializer):
    class Meta:
        fields = tuple(User.REQUIRED_FIELDS) + (
            User.USERNAME_FIELD, User._meta.pk.name, 'password',
            'is_manager',
        )

class CustomUserSerializer(UserSerializer):
    class Meta:
        model = User
        fields = tuple(User.REQUIRED_FIELDS) + (
            User._meta.pk.name,
            User.USERNAME_FIELD,
            'is_manager',
        )
        read_only_fields = (User.USERNAME_FIELD,)

# settings.py
DJOSER = {
    'SERIALIZERS': {
        'user_create': 'users.serializers.CustomUserCreateSerializer',
        'user': 'users.serializers.CustomUserSerializer',
    },
}
```

I receive this error: `ImportError: Module "users.serializers" does not define a "UserSerializer" attribute/class`. 

The traceback leads me back to `class CurrentUserSerializer(settings.SERIALIZERS.user):` in djoser/serializers.py. If I remove that `CurrentUserSerializer` class, or if I change its inherited class to `serializers.ModelSerializer` then everything runs as expected.

My guess is that this is a sort of circular dependency issue with the new CurrentUserSerializer, but I'm not quite sure how to solve it in my code (or if that's possible).

**Comment by dekoza** [comment]
@joshua-s can you please take a closer look?

**Comment by joshua-s** [comment]
@dekoza I am looking into it.

**Comment by joshua-s** [comment]
@dekoza it is definitely the circular import that is creating the issue. We could resolve it either by splitting `CurrentUserSerializer` into another file like @jpdlor or by changing `CurrentUserSerializer` so that it is not a proxy class.

I personally lean towards the latter. We could still include the `DeprecationWarning` on the new serializer, and it would have the same level of visibility. It would also be good to investigate whether there is a better place to put the deprecation warning: like it was said above, it seems a bit strange to "punish" users with a `DeprecationWarning` straight out of the box on a valid endpoint.

**Comment by joshua-s** [comment]
Since this is urgent, I am going to open a PR for the second way and we can revise it from there.

**Comment by nils-wisiol** [comment]
We fixed it for us by having `CurrentUserSerializer` inherit from djoser's `UserSerializer` instead of the settings string. (This was also the case in Djoser before the deprication warning was introduced.)

Thanks for handling this so quick @joshua-s
