### ISSUE TITLE
Get /users/ returns all users by default

### ISSUE THREAD

**Issue by baddar** [sunscrapers/djoser#371]
Hi djoser team

Awesome app you have developed, been using it for a while and just wanted to double check (and maybe have it clarified in the docs), is the endpoint /users/ supposed to just return all users in the system to anyone? 

Meaning if I have **url(r'^auth/', include('djoser.urls')),** in my urls.py, automatically [my domain]/users/ would return all users in the system to anyone, no auth required by default. Of course if we set PERMISSIONS for user_list it won't show but is it not better to default this permission to either **rest_framework.permissions.IsAdminUser** or **djoser.permissions.CurrentUserOrAdmin** instead of **djoser.permissions.CurrentUserOrAdminOrReadOnly**?

Kind Regards
Baddar

**Comment by hawi74** [comment]
Hi,

I agree that the default behaviour should be to NOT let non-staff users get any data about other users. Instead of restricting access to those endpoints, I think that limiting queryset depending on current user role is a better solution - this way, the endpoints will return 404 if the user has no permissions OR user with provided ID does not exist. This prevents getting an idea about how many users are in the system by crawling `/auth/users/<id>/` endpoint and can be easily changed using inheritance. We can consider adding a setting for that, e.g. `LIMIT_USERS_FOR_NON_STAFF` that defaults to `True`.
