### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by iho** [sunscrapers/djoser#39]
Hi!
I use custom user model(inherited from AbstractUser) and I have few errors
http://127.0.0.1:8000/auth/logout
```
'LogoutView' should either include a 'serializer_class' attribute, or use the 'model' attribute as a shortcut for automatically generating a serializer class.
```
http://127.0.0.1:8000/auth/login
```
can only concatenate tuple (not "list") to tuple
```
screenshot http://i.imgur.com/vJ5w9KT.png
```
Django==1.8
djangorestframework==2.4.5
djoser==0.2.1
```

**Comment by haxoza** [comment]
HI! Thanks for submitting the issue with your dependencies. That helps a lot.

As far as I know Django REST Framework 2.4 doesn't support Django 1.8 and that's why you receive the following error:
```
TypeError: can only concatenate tuple (not "list") to tuple
```

I would recommend to upgrade to DRF 3.1 or downgrade to Django 1.7 because we are not going to fix this compatibility issue.

Regarding the `LogoutView` error I noticed that it's thrown on `OPTIONS` request method. It's because of super class which is `GenericAPIView`. I believe it should be changed to `APIView` class. I hope we will fix it soon.

**Comment by haxoza** [comment]
The `LogoutView` error is fixed now. If you want to start using djoser with latest commit please be aware of trailing slashes in `urls.py` introduced in the latest changes.

**Comment by iho** [comment]
@haxoza 
> I would recommend to upgrade to DRF 3.1 or downgrade to Django 1.7 because we are not going to fix this compatibility issue.
Thank you! Your advice help me.
