### ISSUE TITLE
Set User.is_active=False on registration, until activation

### ISSUE THREAD

**Issue by smcoll** [sunscrapers/djoser#4]
User.is_active is being set to True in the registration view.  While a token is not necessarily being granted, the user is still activated.  When ActivationView is hit, is_active is being set to True, when it's already True.

Perhaps is_active should be set to True if LOGIN_AFTER_REGISTRATION is True only.

**Comment by haxoza** [comment]
@smcoll, thanks for creating this issue. I agree that the current behaviour is logically inconsistent.

I think it could be solved in three ways:

1. As @smcoll proposed, `is_active` should be set to `True` if `LOGIN_AFTER_REGISTRATION` is `True` only.
2. Same as above but bind `is_active` flag to `SEND_ACTIVATION_EMAIL ` setting.
3. Introduce new setting `ACTIVATE_AFTER_REGISTRATION` and pass it to `create_user()` call in [`UserRegistrationSerializer.save()`](https://github.com/sunscrapers/djoser/blob/master/djoser/serializers.py#L43) method.

In my opinion option 3. is the best choice, because it keeps `is_active` flag independent which allows easier customization by overriding default djoser classes.

**Comment by konradhalas** [comment]
Or maybe `UserManager.create_user` should create activated or not activated user depending on your business logic? 

Does it make sense to introduce `ACTIVATE_AFTER_REGISTRATION`? What if `SEND_ACTIVATION_EMAIL` will be `True` and `ACTIVATE_AFTER_REGISTRATION` will be `False` ?

**Comment by haxoza** [comment]
> Does it make sense to introduce ACTIVATE_AFTER_REGISTRATION? What if SEND_ACTIVATION_EMAIL will be True and ACTIVATE_AFTER_REGISTRATION will be False ?

Somebody can just send welcome email after registration and have still activated user account.

**Comment by konradhalas** [comment]
True, but we are providing template for this emails, and it's strictly connected with activation process.

**Comment by haxoza** [comment]
Yep, maybe you're right. So adding the notice in README about customization of `create_user()` method on user manager is a fourth solution.

**Comment by Zeioth** [comment]
I did it overriding save method of UserRegistrationSerializer:

```
  def save(self, **kwargs):
        data = self.init_data if hasattr(self, 'init_data') else self.initial_data
        new_user = User.objects.create_user(data['username'],
                                            data['email'],
                                            data['password'])
        new_user.is_active = False
        new_user.save()
        return new_user
```

**Comment by konradhalas** [comment]
Ok, I think we should leave it as it is now, users could overwrite `UserRegistrationSerializer` or `User.objects.create_user` (I think this is better idea).
