### ISSUE TITLE
Return a 401 on failed login (Token authentication)

### ISSUE THREAD

**Issue by C0DK** [sunscrapers/djoser#504]
Currently an HTTP error code 400 is returned upon trying to login with the wrong credentials. To the [best of my knowledge](https://stackoverflow.com/questions/11714485/restful-login-failure-return-401-or-custom-response), the correct error code should be a 401.

This would be lovely to fix.

It should probably be done on the following line:
https://github.com/sunscrapers/djoser/blob/786edc2bb129d7343e54d59b15b682689f534e46/djoser/utils.py#L19

**Comment by C0DK** [comment]
https://github.com/sunscrapers/djoser/blob/master/djoser/serializers.py#L124 

This line needs to be changed. I'll look at creating a pull request.

**Comment by C0DK** [comment]
Sorry for spamming my own issue, but i would suggest raising a [AuthenticationFailed](https://www.django-rest-framework.org/api-guide/exceptions/#authenticationfailed) exception, (which is 403, not 401, but it's less important), which i could easily implement, however i worry that it will break systems that are currently depending on the 400 error, which in my opinion, is the wrong errorcode to use here (it's a bit vague as well). I am waiting for you lovely people to accept that before i will delve into working on such a fix though.

**Comment by C0DK** [comment]
If i create a PR can i assume it will be merged?

**Comment by tomj** [comment]
@C0DK I just hit this myself - and initially I have to assume there's a reason this hasn't been fixed already.  Interested to hear what we come up with.

**Comment by C0DK** [comment]
The solution is simply enough but will potentially be breaking for dependencies.

**Comment by tomwojcik** [comment]
> 401 Unauthorized - The request requires user authentication. The response MUST include a WWW-Authenticate header field (section 14.47) containing a challenge applicable to the requested resource.

> 403 Forbidden - The server understood the request, but is refusing to fulfill it.


I believe it's an old conflict of opinions (sic!). And in my opinion none of them apply here.

It's a REST API we're talking about and "login" endpoint doesn't require an authorization, which 401 indicates. You don't send `Authorization` header. You try to obtain a token POSTing a credentials. If it fails, it's a validation error. And 403 suits better if those credentials are not sufficient.

If anything, 422 suits better but I like 400 more as it's a generic error that's more common for this case.

In DRF you can see 401 here and there but it's because the token has been passed as `Authorization: Token ...`.

https://github.com/encode/django-rest-framework/blob/35c0abf24ea4a6c38e6fc2ee22b4aabe73776783/rest_framework/authentication.py#L89-L106

Therefore what you compare here is apples to oranges. In my opinion `TokenCreateView` should return `400` on invalid credentials and there's nothing to fix.

**Comment by C0DK** [comment]
That is a great point and my opinion is changed. 400 is great. Thank you for taking your time :)
