### ISSUE TITLE
When using DRF OpenAPI we can not assume a self.request is available

### ISSUE THREAD

**Issue by jryannel** [sunscrapers/djoser#506]
```
def get_queryset(self):
    user = self.request.user
    ...
```

will fail when no request is available, which leaves OpenAPI with no way to determine the query set used.

```py
def get_queryset(self):
    if not self.request:
        return User.objects.none()
    ...
```

Fixes this for me.

# How to reproduce:
- Add OpenAPI according to DRF 3.10
- run  ./manage.py generateschema on a djoser project

You should see 

```
UserWarning: <class 'djoser.views.UserViewSet'> is not compatible with schema generation
```

See pull request #505

**Comment by tomwojcik** [comment]
Thanks for opening this ticket. 

Indeed, your solution should be sufficient. It's a very custom request though, that would fix only your specific case. Otherwise, I think we should in general always expect `request` to be there.

Instead of merging this change, I'd rather advise inheriting djosers `UserViewSet` and doing this change in your repo to make it work for your specific case. 

Lastly, djoser works out of the box with [`drf-yasg`](https://github.com/axnsan12/drf-yasg). So it might solve all your problems.
