### ISSUE TITLE
How to log in with email?

### ISSUE THREAD

**Issue by howiezhao** [sunscrapers/djoser#511]
How can I log in with my email and create jwt? 

I read the document and set `LOGIN_FIELD` to `email`, it doesn’t work.

It still prompts for `username`.

**Comment by tomwojcik** [comment]
Can you provide an example of a failing test?

For comparison, here's a test that passes. 

https://github.com/sunscrapers/djoser/blob/6bba95a89875a53d90f4d1f7060ab0edd97d27f8/testproject/testapp/tests/test_token_create.py#L88-L101

**Comment by howiezhao** [comment]
@tomwojcik Thank you for replying to my question.

I read the documentation and found that the following settings are required:

```python
DJOSER = {
    'LOGIN_FIELD': 'email',
}
```

After I set it up, I want to use `curl` to test it:

```
curl -X POST http://127.0.0.1:8000/auth/jwt/create/ --data 'email=a@test.com&password=a'
```

But it returns the following response:

```
{"username":["This field is required."]}
```

I can still use `username` to create jwt, it seems that this setting does not work.

**Comment by tomwojcik** [comment]
You're right, it's won't work for JWT. 

We use `django-rest-framework-simplejwt` for JWT. If you want to use our lib without much hassle out-of-the-box, you can use it as is. But it doesn't mean you will be able to configure this JWT endpoint using our settings as it's 3rd party we're talking about.

https://github.com/sunscrapers/djoser/blob/6bba95a89875a53d90f4d1f7060ab0edd97d27f8/djoser/urls/jwt.py#L1-L12

So [`django-rest-framework-simplejwt` docs](https://django-rest-framework-simplejwt.readthedocs.io/en/latest/) apply here. 

Here's SO question [How can I use `email` in “django-rest-framework-simplejwt” instead of `username` to generate token?](https://stackoverflow.com/questions/54157056/how-can-i-use-email-in-django-rest-framework-simplejwt-instead-of-username)

Thanks for pointing that out. It definitely has to be addressed in our docs.

**Comment by howiezhao** [comment]
@tomwojcik Ok i got it, thank you very much for your reply
