### ISSUE TITLE
how to Log in automatically after registration

### ISSUE THREAD

**Issue by stfenjobs** [sunscrapers/djoser#532]

**Comment by stfenjobs** [comment]
i fix:

custom UserCreateSerializer:

```python
class UserCreateSerializer(UserCreateSerializer):
    def perform_create(self, validated_data):
        with transaction.atomic():
            user = User.objects.create_user(**validated_data)

        new_user = authenticate(username=validated_data.get('username'),
                                password=validated_data.get('password'),
                                )
        if new_user is not None:
            login(self.context.get("request"), new_user)
        return user
```

**Comment by FedericoCapaldo** [comment]
@stfenjobs shouldn't the UserCreateSerializer somehow return the auth token so that a SPA that logs in upon registration to Django DRF with Djoser then can authenticate further requests later? as of not it only `return user` which contains the user fields but no token.

So how does this authentication upon signup works for you?

**Comment by stfenjobs** [comment]
@FedericoCapaldo 
hi,  in SPA, i used **session** , not **token** ,  i used it on my website,  i don't have mobile APP

i don't know how to return a **token**

------
my english is not well, i use google translate
