### ISSUE TITLE
Can't Access Django  Admin With Djoser JwtAuthentication 

### ISSUE THREAD

**Issue by 4k45hv3rm4** [sunscrapers/djoser#568]
hi, I have implemented a djoser User Autentication(Custom user model with email as username) in my project and I am trying to access Django Admin using superuser I created but I am unable to access it , It says invalid login /password , or invalid credentials. Can Someone please tell why is this happening , I tried searching about this a lot but I am unable to get through this . This superuser has is_staff =True and is_superuser=True and is_active=True, then also its not allowing to access Django Admin.
Can someone please look to this issue and resolve !!!

**Comment by haxoza** [comment]
Django Admin has nothing to do with Djoser (and DRF) so I believe you either messed up your custom User model or you just confused [DRF's default auth classes](https://www.django-rest-framework.org/api-guide/settings/#default_authentication_classes) with [Django's auth backends](https://docs.djangoproject.com/en/3.1/ref/settings/#std:setting-AUTHENTICATION_BACKENDS) settings.

Closing this issue because it is not a djoser related.

**Comment by 4k45hv3rm4** [comment]
> Django Admin has nothing to do with Djoser (and DRF) so I believe you either messed up your custom User model or you just confused [DRF's default auth classes](https://www.django-rest-framework.org/api-guide/settings/#default_authentication_classes) with [Django's auth backends](https://docs.djangoproject.com/en/3.1/ref/settings/#std:setting-AUTHENTICATION_BACKENDS) settings.
> 
> Closing this issue because it is not a djoser related.

Yeah , I messed up with custom user model . Thanks, It was solved
