### ISSUE TITLE
Remove `LOGIN_AFTER_*` settings

### ISSUE THREAD

**Issue by konradhalas** [sunscrapers/djoser#57]
Reasons:

1) those settings increase code complexity too much, 
2) you could just make login request after registration/activation.

Refs: discussion in #56 PR.

**Comment by haxoza** [comment]
The point 2. is not so obvious for activation functionality.

Login request requires user's credentials. I would agree that just after registration you can easily immediately send login request. It's possible because from code perspective you still keep user's credentials in local scope.

When it comes to sending login request just after activation it's not so simple from code perspective. I can imagine that it's highly possible that you don't keep user's credentials in local scope anymore. Of course it depends on your code design but I suppose it's a common pattern in many apps or frameworks.

I'm not sure yet what influence these `LOGIN_AFTER_*` functionalities will have for adding support for other auth backends. For now I opt in for not removing these features until we face other auth backends.

**Comment by konradhalas** [comment]
Ok, for now we can hold it. You have right, that `LOGIN_AFTER_ACTIVATAION` make sense (a little bit).

**Comment by haxoza** [comment]
I decided to remove this settings due to fact that there is no easy and clean way to integrate this functionalities with other auth backends (#30 & #40).

Those settings could be replaced with easier serializers customization at some point.
