### ISSUE TITLE
Please Publish new version to PyPi

### ISSUE THREAD

**Issue by adityaprakashgupta** [sunscrapers/djoser#703]
The version of Djoser on PyPI is 2.1.0
which was released in 2020.
Please update with new commits.

**Comment by spockNinja** [comment]
For now, I'll be pointing at a commit, which is less than ideal.

We have the technology to automate this process. We can use a GitHub action that only triggers on the creation of a new tag. If a PR for that would help get this done, I'd be happy to help.

There still seems to be plenty of community interest around this library. Does anyone know who the bottleneck is and if we can hand the repo off to someone who wants to make sure it is maintained?

**Comment by tomwojcik** [comment]
I will be the maintainer from now on, but I can work on Djoser only for a few hours a month, so don't expect too much. I will automate as much as possible so releases should be seamless. If you find an issue, please follow with a PR. 

2.2.0a0 has been released. https://pypi.org/project/djoser/2.2.0a0/#description Please let me know if it works. The build and release process was a mess and changed drastically since I released Djoser the last time (3 years ago), so some stuff might not work as expected.

**Comment by tomwojcik** [comment]
No feedback wrt 2.2.0a0 so I assume everything is working as expected. 2.2.0 released https://pypi.org/project/djoser/
