### ISSUE TITLE
AttributeError at /auth/register

### ISSUE THREAD

**Issue by ansal** [sunscrapers/djoser#8]
AttributeError at /auth/register
    'UserRegistrationSerializer' object has no attribute 'init_data'

I was trying to create a new user by issuing a POST request to /auth/register. Exception location is at djoser/djoser/serializers.py in save, line 34

Here are my package versions -

    Django==1.7.1
    djangorestframework==3.0.0
    djoser==0.1.0

Can you tell me why this is happenning?

**Comment by konradhalas** [comment]
Hi @nigelsmith! Thank you for your comment!

Yep, you are right - `initial_data` are unvalidated and they shouldn't be used here. Furthermore, this is internal serializer API. Unfortunately, there is no easy way to access validated data in `save` or `save_object` method (DRF2). As you pointed out, this problem is fixed in DRF3. One of reasons why DRF author changed it, fit very well into `djoser` issue - DRF3 changelog:

> Instantiating model instances directly means that you cannot use model manager classes for instance creation, e.g. `ExampleModel.objects.create(...)`. Manager classes are an excellent layer at which to enforce business logic and application-level data constraints.

If we still want to use `User.objects.create_user` (which is good idea IMHO) we could call it in `restore_object` method:

```python
def restore_object(self, attrs, instance=None):
    return User.objects.create_user(**attrs)
```

... but in this case we also have to override `save_object` method:

```python
def save_object(self, obj, **kwargs):
    return obj
```

... because it uses `obj.save(force_insert=True)`, which will raise `IntegrityError` in this case (user was created in `restore_object`). But even if we choose this option (which I don't like), there will be problem with DRF3:

> AssertionError: Serializer `djoser.serializers.UserRegistrationSerializer` has old-style version 2 `.restore_object()` that is no longer compatible with REST framework 3. Use the new-style `.create()` and `.update()` methods instead.

Maybe we should create different classes for DRF2 and DRF3 (we could check `rest_framework.VERSION`)? We could also move creation step into view `create` method, but this will be also problematic - DRF3 has different flow in this method.

**Comment by haxoza** [comment]
I agree that using `User.objects.create_user` here is a good practice. It delegates user creation responsibility to default behaviour of Django auth system.

Considering assertions in DRF3 that prevents overriding DRF2 methods of serializer class I think that @konradhalas suggestion about providing different classes for different DRF versions is actually a good idea. It looks like there is no other choice.

**Comment by konradhalas** [comment]
Ok, thanks - I will try to come up with sth.

**Comment by konradhalas** [comment]
Fixed https://github.com/sunscrapers/djoser/commit/4b9593b315b88add4a1970352779356eb85d2457
