### ISSUE TITLE
No Redirect After Successful Login

### ISSUE THREAD

**Issue by freedombird9** [sunscrapers/djoser#88]
Hi, I'm using django rest_framework with djoser. Whenever I went to /login with a 'next=' parameter to specify the redirect url, it fails. After successful login, I can just see the returned access token, without the page turning. I want to know if this issue is related to djoser? Because I've done some research and people says a custom login template is needed for url redirection, I don't see how to do it in djoser documentation.

**Comment by apokinsocha** [comment]
Djoser is DRF/REST API based.
since you will be calling the endpoints asynchronously probably on the client side (ie: AJAX/javascript), it's up to you to redirect on the client side after successful login.
If you're referring to the DRF browsable API, in that case yes, you will need to setup a template and probably another view, but that is more to do with DRF than with Djoser. Please look at DRF http://www.django-rest-framework.org/topics/browsable-api/ documentation on how to make the modifications.

**Comment by konradhalas** [comment]
Thank you @freedombird9 for your feedback and thank you @apokinsocha for a correct answer :)
